# Generated by Django 5.1.7 on 2025-03-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dailylog_rest_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='total_driving_time',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
