# Generated by Django 5.1.7 on 2025-03-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dailylog_memo_alter_dailylog_current_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='createdOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='createdOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_driving_time',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
