# Generated by Django 5.1.7 on 2025-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
