# Generated by Django 5.1.7 on 2025-03-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='daily_logs',
        ),
    ]
