# Generated by Django 5.1.7 on 2025-03-26 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trip_end_time_alter_trip_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='rest_breaks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
