# Generated by Django 5.1.7 on 2025-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dailylog_rest_breaks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='memo',
            field=models.CharField(default='memo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='current_location',
            field=models.CharField(max_length=100),
        ),
    ]
